/** @type {import('tailwindcss').Config} */
// GENERATED by scripts/tailwind-precompile.py - rerun that rather than hand-editing.
// Build: <tailwindcss> -c tailwind.config.js -i src/input.css -o styles.css --minify
// Replaces the runtime cdn.tailwindcss.com JIT compiler with a precompiled stylesheet.
// Any class added to this site LATER needs a rebuild or it will not exist in the CSS.
module.exports = {
    theme: {
      extend: {
        colors: {
          brand: {
            orange: "#E66A2C",
            "orange-soft": "#F08A4A",
            rust: "#8B2A1A",
            "rust-deep": "#5C1B11",
            charcoal: "#1A1614",
            "charcoal-2": "#2A2421",
            cream: "#F5EFE6",
            sand: "#E8DDC9",
            "sand-2": "#D8C9AE",
          },
        },
        fontFamily: {
          display: ["Archivo", "system-ui", "sans-serif"],
          condensed: ["\"Archivo Narrow\"", "Archivo", "system-ui", "sans-serif"],
          body: ["Inter", "system-ui", "sans-serif"],
        },
        boxShadow: {
          "rust-sm": "0 1px 2px rgba(26,22,20,0.06), 0 4px 10px rgba(26,22,20,0.06)",
          "rust-md": "0 2px 4px rgba(26,22,20,0.06), 0 8px 20px rgba(26,22,20,0.08)",
          "rust-lg": "0 4px 10px rgba(26,22,20,0.08), 0 16px 36px rgba(26,22,20,0.10)",
          "inset-line": "none",
        },
      },
    },
    content: ["./*.html", "./reblocking-quote/*.html", "./restumping-quote/*.html"],
  }
